### ISSUE TITLE
Interface não suportada

### ISSUE THREAD

**Issue by Ljordison** [Daniel09Fernandes/ComponentDinosOffice-OpenOffice#21]
Delphi 10.2 Tokyo está dando erro de interface não suportada

**Comment by Daniel09Fernandes** [comment]
Neste caso, ao adicionar o path deu erro adiciona na, chave, no registro do windows.

Aperta Win + R, digita regedit e clica em OK

No meu caso aqui (RAD Studio 2010) fica em:
HKEY_CURRENT_USER\Software\CodeGear\BDS\7.0\Library

e adiciona em "Search Path".
